services:
  manpromanpro:
    container_name: manpromanpro
    build:
      context: .
      dockerfile: ManproManproDockerfile
    ports:
      - '11001:8081'
    restart: 'no'
    labels:
      uid: "2206082114"
    networks:
      - backend-network